/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CTokenRouteImport } from './routes/c/$token'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedFluxoRouteImport } from './routes/_authenticated/fluxo'
import { Route as AuthenticatedDesignRouteImport } from './routes/_authenticated/design'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as ApiPublicTmpResetBiaRouteImport } from './routes/api/public/_tmp-reset-bia'
import { Route as AuthenticatedClientsClientIdIndexRouteImport } from './routes/_authenticated/clients/$clientId/index'
import { Route as ApiPublicHooksCleanupMediaRouteImport } from './routes/api/public/hooks/cleanup-media'
import { Route as AuthenticatedPostsPostIdEditRouteImport } from './routes/_authenticated/posts/$postId/edit'
import { Route as AuthenticatedDashboardDayDateRouteImport } from './routes/_authenticated/dashboard.day.$date'
import { Route as AuthenticatedClientsClientIdNewRouteImport } from './routes/_authenticated/clients/$clientId/new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFluxoRoute = AuthenticatedFluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignRoute = AuthenticatedDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicTmpResetBiaRoute = ApiPublicTmpResetBiaRouteImport.update({
  id: '/api/public/_tmp-reset-bia',
  path: '/api/public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsClientIdIndexRoute =
  AuthenticatedClientsClientIdIndexRouteImport.update({
    id: '/clients/$clientId/',
    path: '/clients/$clientId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksCleanupMediaRoute =
  ApiPublicHooksCleanupMediaRouteImport.update({
    id: '/api/public/hooks/cleanup-media',
    path: '/api/public/hooks/cleanup-media',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPostsPostIdEditRoute =
  AuthenticatedPostsPostIdEditRouteImport.update({
    id: '/posts/$postId/edit',
    path: '/posts/$postId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDayDateRoute =
  AuthenticatedDashboardDayDateRouteImport.update({
    id: '/day/$date',
    path: '/day/$date',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedClientsClientIdNewRoute =
  AuthenticatedClientsClientIdNewRouteImport.update({
    id: '/clients/$clientId/new',
    path: '/clients/$clientId/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/design': typeof AuthenticatedDesignRoute
  '/fluxo': typeof AuthenticatedFluxoRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/c/$token': typeof CTokenRoute
  '/api/public': typeof ApiPublicTmpResetBiaRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/clients/$clientId/new': typeof AuthenticatedClientsClientIdNewRoute
  '/dashboard/day/$date': typeof AuthenticatedDashboardDayDateRoute
  '/posts/$postId/edit': typeof AuthenticatedPostsPostIdEditRoute
  '/api/public/hooks/cleanup-media': typeof ApiPublicHooksCleanupMediaRoute
  '/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/design': typeof AuthenticatedDesignRoute
  '/fluxo': typeof AuthenticatedFluxoRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/c/$token': typeof CTokenRoute
  '/api/public': typeof ApiPublicTmpResetBiaRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/clients/$clientId/new': typeof AuthenticatedClientsClientIdNewRoute
  '/dashboard/day/$date': typeof AuthenticatedDashboardDayDateRoute
  '/posts/$postId/edit': typeof AuthenticatedPostsPostIdEditRoute
  '/api/public/hooks/cleanup-media': typeof ApiPublicHooksCleanupMediaRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/design': typeof AuthenticatedDesignRoute
  '/_authenticated/fluxo': typeof AuthenticatedFluxoRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/c/$token': typeof CTokenRoute
  '/api/public/_tmp-reset-bia': typeof ApiPublicTmpResetBiaRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/clients/$clientId/new': typeof AuthenticatedClientsClientIdNewRoute
  '/_authenticated/dashboard/day/$date': typeof AuthenticatedDashboardDayDateRoute
  '/_authenticated/posts/$postId/edit': typeof AuthenticatedPostsPostIdEditRoute
  '/api/public/hooks/cleanup-media': typeof ApiPublicHooksCleanupMediaRoute
  '/_authenticated/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/design'
    | '/fluxo'
    | '/tasks'
    | '/c/$token'
    | '/api/public'
    | '/clients/'
    | '/dashboard/'
    | '/clients/$clientId/new'
    | '/dashboard/day/$date'
    | '/posts/$postId/edit'
    | '/api/public/hooks/cleanup-media'
    | '/clients/$clientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/design'
    | '/fluxo'
    | '/tasks'
    | '/c/$token'
    | '/api/public'
    | '/clients'
    | '/dashboard'
    | '/clients/$clientId/new'
    | '/dashboard/day/$date'
    | '/posts/$postId/edit'
    | '/api/public/hooks/cleanup-media'
    | '/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/design'
    | '/_authenticated/fluxo'
    | '/_authenticated/tasks'
    | '/c/$token'
    | '/api/public/_tmp-reset-bia'
    | '/_authenticated/clients/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/clients/$clientId/new'
    | '/_authenticated/dashboard/day/$date'
    | '/_authenticated/posts/$postId/edit'
    | '/api/public/hooks/cleanup-media'
    | '/_authenticated/clients/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CTokenRoute: typeof CTokenRoute
  ApiPublicTmpResetBiaRoute: typeof ApiPublicTmpResetBiaRoute
  ApiPublicHooksCleanupMediaRoute: typeof ApiPublicHooksCleanupMediaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fluxo': {
      id: '/_authenticated/fluxo'
      path: '/fluxo'
      fullPath: '/fluxo'
      preLoaderRoute: typeof AuthenticatedFluxoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design': {
      id: '/_authenticated/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AuthenticatedDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/_tmp-reset-bia': {
      id: '/api/public/_tmp-reset-bia'
      path: '/api/public'
      fullPath: '/api/public'
      preLoaderRoute: typeof ApiPublicTmpResetBiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/$clientId/': {
      id: '/_authenticated/clients/$clientId/'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof AuthenticatedClientsClientIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/cleanup-media': {
      id: '/api/public/hooks/cleanup-media'
      path: '/api/public/hooks/cleanup-media'
      fullPath: '/api/public/hooks/cleanup-media'
      preLoaderRoute: typeof ApiPublicHooksCleanupMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/posts/$postId/edit': {
      id: '/_authenticated/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof AuthenticatedPostsPostIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/day/$date': {
      id: '/_authenticated/dashboard/day/$date'
      path: '/day/$date'
      fullPath: '/dashboard/day/$date'
      preLoaderRoute: typeof AuthenticatedDashboardDayDateRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/clients/$clientId/new': {
      id: '/_authenticated/clients/$clientId/new'
      path: '/clients/$clientId/new'
      fullPath: '/clients/$clientId/new'
      preLoaderRoute: typeof AuthenticatedClientsClientIdNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardDayDateRoute: typeof AuthenticatedDashboardDayDateRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardDayDateRoute: AuthenticatedDashboardDayDateRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedDesignRoute: typeof AuthenticatedDesignRoute
  AuthenticatedFluxoRoute: typeof AuthenticatedFluxoRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedClientsClientIdNewRoute: typeof AuthenticatedClientsClientIdNewRoute
  AuthenticatedPostsPostIdEditRoute: typeof AuthenticatedPostsPostIdEditRoute
  AuthenticatedClientsClientIdIndexRoute: typeof AuthenticatedClientsClientIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedDesignRoute: AuthenticatedDesignRoute,
  AuthenticatedFluxoRoute: AuthenticatedFluxoRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedClientsClientIdNewRoute: AuthenticatedClientsClientIdNewRoute,
  AuthenticatedPostsPostIdEditRoute: AuthenticatedPostsPostIdEditRoute,
  AuthenticatedClientsClientIdIndexRoute:
    AuthenticatedClientsClientIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CTokenRoute: CTokenRoute,
  ApiPublicTmpResetBiaRoute: ApiPublicTmpResetBiaRoute,
  ApiPublicHooksCleanupMediaRoute: ApiPublicHooksCleanupMediaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
